### ISSUE TITLE
Hashid and Rails 5?

### ISSUE THREAD

**Issue by kevinhofmaenner** [jcypret/hashid-rails#11]
Hi first off, thanks for this gem. I had a question regarding using this with Rails 5. Rails5 requires activerecord 5 (duh) but it looks like this gem depends on activerecord (~> 4.0). This causes Bundler to  not find compatible versions for activerecord.

Any way to get this working in Rails5? (I'm new to this process so apologies if I missed something or this isn't the right forum for this).

Thanks!

**Comment by jcypret** [comment]
I hadn't actually used it with that version of Rails yet. I've pushed a new version of the gem that works with Rails 5. I didn't run into any compatibility issues. Thanks for the input!
