### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by DannyBen** [jcypret/hashid-rails#13]
Hey - is this considered production ready?

**Comment by jcypret** [comment]
I've been using it on a large production app for the past year without issue. Before that I was using the code as a concern with essentially the same code. The entire library is about 80 lines long (https://github.com/jcypret/hashid-rails/blob/master/lib/hashid/rails.rb) and is essentially a convenience wrapper for the Hashid project.

**Comment by DannyBen** [comment]
Thanks. It does look soliid, I only had to stop using it due to #14
