### ISSUE TITLE
RecordNotFound with fixtures, when secret is configured

### ISSUE THREAD

**Issue by DannyBen** [jcypret/hashid-rails#16]
Hi,

When working without any `Hashid` configuration, things work properly.

After adding an initializer with this:

```ruby
# config/initializers/hashids.rb
Hashid::Rails.configure do |config|
  config.secret = 'hello'
  # config.length = 8
end
```

I am getting this error:
```
ActiveRecord::RecordNotFound: Couldn't find SomeModel with an out of range ID
```

The call that makes it fail is always a fixtures call, like:

```ruby
task = tasks :some_task
```

Changing the secret string, makes it fail for different fixtures, and succeed for previously failing fixtures.

A little byebug session to further illustrate:

```ruby
[43, 52] in /.../task_policy_test.rb
   46:   test "fotbid change_notification" do
   47:     byebug
=> 48:     refute_permit users(:user), tasks(:patrol), :change_notification?
   49:   end

(byebug) tasks :patrol # fail
*** ActiveRecord::RecordNotFound Exception: Couldn't find Task with an out of range ID

nil

(byebug) Task.find_by subject: 'Patrol the building' # pass
#<Task id: 201007985, subject: "Patrol the building", ...>

```

**Comment by jrasanen** [comment]
Couldn't replicate the issue, my local configuration is:

```ruby
Hashid::Rails.configure do |config|
  config.secret = 'QNq5DY1.g~`i5q4C"2D9Z.s3{X3e5-'
  config.length = 12
end
```

**Comment by DannyBen** [comment]
I can confirm. With `config.length = 12` it works.
Try it without defining length, and it should break.

I would expect it to handle it properly. Not sure if its a hashids issue or hashid-rails issue.

**Comment by jrasanen** [comment]
Still can't replicate. I tried removing it, it seems to [default to 6](https://github.com/jcypret/hashid-rails/blob/master/lib/hashid/rails.rb#L73) if config length is omitted.

And if the length is incorrect, it raises an exception ["Hashids::MinLengthError (The min length must be a Fixnum)"](https://github.com/peterhellberg/hashids.rb/blob/master/lib/hashids.rb#L261-L268)

**Comment by DannyBen** [comment]
Now I can't replicate it either....

**Comment by DannyBen** [comment]
I guess you can close this ticket for now. Dont know what caused this behavior in the first place and why it is not reproducible. I will post again if I manage to reproduce more reliably.

**Comment by jcypret** [comment]
Sounds good :+1:
