### ISSUE TITLE
support for "-" in id

### ISSUE THREAD

**Issue by jtoy** [jcypret/hashid-rails#17]
so you can do params like:
def to_param
  "#{hashid}-#{title}"
end

anyone else need this?

**Comment by jcypret** [comment]
The code you wrote above should work. You can override `to_param` to include the title (provided your model has a `title` attribute). `hashid` is available as an instance method.

```ruby
def to_param
  # `hashid` is available as an instance method. 
  "#{hashid}-#{title}"
end
```

You could then lookup the record by splitting on the hyphen.

```ruby
hashid, _title = params[:id].split('-') 
# or hashid = params[:id].split('-').first
@post = Post.find(hashid)
```
