### ISSUE TITLE
Add Rails 5 support

### ISSUE THREAD

**Issue by jcypret** [jcypret/hashid-rails#19]
Not sure what it needs, but the build fails against the ActiveRecord 5.x series.

**Comment by bingxie** [comment]
I am using activerecord (5.0.0.1), I found it works well.

**Comment by aaronstillwell** [comment]
I'm also using with active record 5 without issue, although I'm obviously having to lock to v0.4.0.

Looks like this is just a test issue - active record doesn't like the FakeConnection class being used to mock a database connection in the test setup.

https://github.com/jcypret/hashid-rails/blob/master/spec/hashid/rails_spec.rb#L176-L184

**Comment by jcypret** [comment]
Thanks for the feedback @bingxie @aaronstillwell! I've pushed a new version of them gem with Rails 5 compatibility. I adjusted the fake model setup as pointed out by @aaronstillwell.
