### ISSUE TITLE
Pack as concern

### ISSUE THREAD

**Issue by adisos** [jcypret/hashid-rails#2]
Not all models need this functionality, I think it would be better convert it to model concern. And include when it needed.

**Comment by franklinyu** [comment]
@adisos Maybe you would like to look at [brianpetro/hashids_rails](https://github.com/brianpetro/hashids_rails).

**Comment by daau** [comment]
@jcypret Any plans to use ActiveSupport::Concerns? Not necessary of course since the codebase is already short and clean, but it does make it a bit more elegant.
