### ISSUE TITLE
Why finding if decoding return nil?

### ISSUE THREAD

**Issue by robinvdvleuten** [jcypret/hashid-rails#23]
Hi there,

When I pass an Hashid that decodes to nil, the find method is still called thus an extra unneeded database query. Is this expected behaviour?

Cheers!

**Comment by jcypret** [comment]
@robinvdvleuten That's not expected behavior. We've pushed a new release that simplifies the find override. I wasn't able to replicate but I'd expect it to work correctly in the new version. Alternatively you can try the `find_by_hashid` and `find_by_hashid!` methods.
