### ISSUE TITLE
Include hashid in individual models instead of globally

### ISSUE THREAD

**Issue by jcypret** [jcypret/hashid-rails#25]
The current implementation includes the Hashid functionality into ActiveRecord::Base. I would like to instead use an explicit include any any models where needed.

**Comment by SirRawlins** [comment]
Having this same thought myself, wanting to drop this into a sizable application and feels like hitting AR::Base risks breaking things elsewhere in the app.

**Comment by jcypret** [comment]
This has been implemented and is available in the latest release.
