### ISSUE TITLE
Trouble with eager loading

### ISSUE THREAD

**Issue by echan00** [jcypret/hashid-rails#31]
Having trouble with eager loading and using hashid.

`@item = Item.includes(:addons, {:addons => :sides}).find_by_hashid(params[:id])`
This will work only if params is a hashid, not an integer id. Otherwise "Couldn't find Item"

`@item = Item.includes(:addons, {:addons => :sides}).find(params[:id])`
This will work only if params is an integer id, not a hashid. Otherwise "record is not found"

**Comment by olliebennett** [comment]
Which version of `hashid-rails` are you using? What is the behaviour you're expecting?

Also (probably not related) but I'm not familiar with the syntax you're using in `includes`; does it work if you just do

```
@item = Item.includes(addons: :sides).etc
```

(without the initial `:addons` param)?

**Comment by echan00** [comment]
hashid-rails (0.7.0)

The extra {:addons => :sides} param also includes the sides model within the addons model. Without this additional param and only the following:
`@item = Item.includes(:addons).find_by_hashid(params[:id])`

Still has issues.

**Comment by jcypret** [comment]
I've pushed up a new version (1.1.1) that addresses this issue. It's fixed here: https://github.com/jcypret/hashid-rails/pull/39.
