### ISSUE TITLE
FYI - 1.0 breaks compatibility with 0.5

### ISSUE THREAD

**Issue by ezuk** [jcypret/hashid-rails#32]
Hi there,

I resolved this for myself by downgrading back to 0.5 but just figured I'd leave a little note here for anyone who follows.

I have a project in production using HashIDs -- it's how we resolve URLs. Thousands of URLs. Today I upgraded to Rails 5 and in the process upgraded from 0.4.1 to 1.0.0. The config key names changed, I updated them (couldn't find anything in the docs for that but it was pretty simple to figure out).

But even though I kept the values the same (only updated names), old HashIDs just stopped resolving. The secret is the same ,min length is the same, etc -- but find_by_hashid with a valid old hash ID just wouldn't work.

As mentioned, the fix was to drop back to 0.5.0 (so 0.4.1 -> 0.5.0 is fine).

**Comment by frederickdubois** [comment]
Currently in the process of upgrading here too, and noticed that the previous `config.secret` seems to have been replaced by `config.salt` but nothing indicates if they act the same or if it's just impossible to maintain the previous ids...

**Comment by ezuk** [comment]
I used the new options, no errors were indicated, everything just broke :)

**Comment by olliebennett** [comment]
From my investigation, I believe the latest version uses a new special prefix for all generated hashids (i.e. it encodes `[42, your_id]` vs just encoding `your_id`) so as to avoid accidental decoding of numeric hashids.

See https://github.com/jcypret/hashid-rails/issues/30 for my proposed solution.

**Comment by jcypret** [comment]
@ezuk Just merged in a PR (https://github.com/jcypret/hashid-rails/pull/37) from @olliebennett that addresses this. There is a new config option to disable hashid signing for backwards compatibility. I've also added some additional notes to the README explaining the upgrade process.
