### ISSUE TITLE
Uncaught exception: uninitialized constant Hashid

### ISSUE THREAD

**Issue by davideghz** [jcypret/hashid-rails#34]
I've been using your gem w/o any issue in my code until I decided to move configuration in an initializer:

*/config/initializers/hashid.rb*
```
Hashid::Rails.configure do |config|
  # The salt to use for generating hashid. Prepended with table name.
  config.salt = "this is my salt"

  # The minimum length of generated hashids
  config.min_hash_length = 6

  # The alphabet to use for generating hashids
  config.alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
end
```
I get following error on startup: `Uncaught exception: uninitialized constant Hashid`

**Comment by olliebennett** [comment]
Did you restart your server after `bundle`-ing? If you're using Spring did you `spring stop`? My initialiser is exactly like yours (using `hashid-rails 0.7.0`).

**Comment by jcypret** [comment]
Hi @davideghz I was not able to replicate this issue you mentioned. Generated a fresh Rails app, added `hashid-rails` to the `Gemfile`, then pasted in the initializer you provided. Scaffolded a model and did not encounter any errors. I second what @olliebennett recommended. Double check that the gem is in your gemfile, run bundle install, and restart the servers (with Spring if you're using it). If the issue persists, would be interested in hearing the steps you took. Without being able to replicate my hands are tied.
