### ISSUE TITLE
Using hashid in ActiveRecord "where" clause doesn't work

### ISSUE THREAD

**Issue by watzon** [jcypret/hashid-rails#36]
I am attempting to use hashid's with `ActiveRecord.where` clauses and it's not working. Is there any way to decode a hashid created this way? Then I could just do `Model.where(parent_id: decoded_hash_id)`.

**Comment by jcypret** [comment]
The `Model.decode_id` method can be use to decode a hashid outside of a finder: 
```ruby
Model.where(parent_id: Model.decode_id(params[:id]))
```

**Comment by thisislorne** [comment]
You know what would save me lots of time? If this was in the readme!
