### ISSUE TITLE
Use secure salt for generating HashIDs object

### ISSUE THREAD

**Issue by olliebennett** [jcypret/hashid-rails#4]
This gem uses the `table_name` of the model as the salt for encoding HashIDs. It's great that the hash used differs between models (by depending on the table name), but it would be more secure to use something unique to the server in addition.

What do you think about concatenating a secret server key into the salt, like so:

```ruby
hashids = Hashids.new("#{table_name}#{ENV['SECRET_KEY_BASE']}")
```

We should use something more secure; if not the `SECRET_KEY_BASE` then something configured via `initializers/hashids.rb` or similar?

Update:

I'm considering using `ENV['HASHIDS_SALT']` - the reason being, if I ever need to reset my `secret_key_base`, I will not invalidate all my HashIDs. I also feel slightly uncomfortable using my secret key as (part of) my salt, because I know HashIDs aren't designed for security, and - although I doubt it's feasible - I can imagine someone reverse engineering my `secret_key_base` if they had a set of my HashIDs from which to brute force it.

**Comment by jcypret** [comment]
@olliebennett I've merged in new code on Master that will allow you to set a custom salt and a custom length using an initializer. I will be pushing the new version within the next day or two. Thanks for the suggestion!
