### ISSUE TITLE
Release 1.1.1 from Master Branch

### ISSUE THREAD

**Issue by olliebennett** [jcypret/hashid-rails#42]
Currently [this commit](https://github.com/jcypret/hashid-rails/commit/fb0f112afb036c1ea4388ad3b5402bf084a67766) bumps the version to `1.1.1` - as released on [RubyGems](https://rubygems.org/gems/hashid-rails/versions/1.1.1).

Master is still showing 1.1.0 because the [eager-loading branch](https://github.com/jcypret/hashid-rails/tree/eager-loading) isn't fully merged (looks like the changes were cherry-picked without the version bump + changlog commit).

**Comment by jcypret** [comment]
Weird, not sure how that happened. I merged the branch into master before releasing: https://github.com/jcypret/hashid-rails/pull/39

Must have got my wired crossed somewhere. I've gone back and merged it in: https://github.com/jcypret/hashid-rails/commit/9655111bae11897f6738dd1791eb6b349f45c4a2 

Good catch!
