### ISSUE TITLE
Consistent between db loads?

### ISSUE THREAD

**Issue by NicoleGriesmeyer** [jcypret/hashid-rails#44]
More of a question than an issue... I'm just wondering if the database is wiped, is there a way to make the hashes generate the same each time for a given model? Perhaps based on a unique field like a name? I see the salt config but it is more of a global config and only part of the generation picture. Just wondering if there's a way to do that. Thanks!

**Comment by jcypret** [comment]
Hi @NicoleGriesmeyer ! The hashids are generated based on the `id` column, so as long as a given model has the same `id` attribute, it will also have the same `hashid`. The salt used to generate the hashid is uses the model name combined with the salt provided in the configuration:

https://github.com/jcypret/hashid-rails/blob/daa14d9e2d7897b7606a1bb01c955b2522fff45f/lib/hashid/rails/configuration.rb#L21

For a `Project` model and a global salt of "123", the salt used for the `Project` model would be "projects123". If you have three records with ids 1, 2, 3, delete them, then recreate records with ids 1, 2, 3, the hashids would be the same despite the database being wiped.

**Comment by NicoleGriesmeyer** [comment]
Awesome! Thank you for the help very much!
