### ISSUE TITLE
Error ActiveRecord::RecordNotFound with fixtures - 2018 edition

### ISSUE THREAD

**Issue by DannyBen** [jcypret/hashid-rails#45]
Hi,

It seems like an old bug I found a year and a half ago (in #16) has resurfaced.
It is now easily reproducible.

When using fixtures, and setting `config.sign_hashids` to `false`, tests fail with an error like this:

```
ActiveRecord::RecordNotFound: Couldn't find User without an ID
```

For convenience, I have created an [example repo][1] that demonstrates the problem.

Also, for context, I should probably mention that I am disabling `sign_hashids` since I need compatibility with previous version, since I cannot afford my IDs to change (at least in one of my apps).

If any additional information is required, let me know.

[1]: https://github.com/DannyBen/temp-hashids-debug

**Comment by jcypret** [comment]
I've opened a PR to fix this issue: https://github.com/jcypret/hashid-rails/pull/46/files

I appreciate the test app. That helped me to quickly figure out the issue. 

Let me know if this works for you:

```ruby
gem 'hashid-rails', github: "jcypret/hashid-rails", branch: "unsigned-rails-fixtures"
```

If so, I'll get a patch release out.

**Comment by DannyBen** [comment]
Yes. This seems to fix it.

I noticed another difference, although this is not a big deal (and a separate issue, if at all one). With this:

```ruby
config.min_hash_length = 8
config.sign_hashids = true
```

you get a 9 character long ID, whereas with this:

```ruby
config.min_hash_length = 8
config.sign_hashids = false
```

you get an 8 character long ID.

(I have updated the repo with another test for that, if it helps)

**Comment by jcypret** [comment]
@DannyBen That variance is expected. The `min_hash_length` sets the minimum but builds larger hashids if needed. The Rails fixtures use large integers so it's pushing the hashid to nine characters.

```
Loading development environment (Rails 5.1.4)
>> User.encode_id(980190962)
=> "W85rRxvq"
>> Hashid::Rails.configuration.sign_hashids = true
=> true
>> User.encode_id(980190962)
=> "9YID3vMJy"
>> User.encode_id(98019096)
=> "6YEIBgY3"
>> User.encode_id(1)
=> "1X9YIGXz"
```
Reducing the ID down to 8 digits or less drops the hashid length down to 8.

**Comment by jcypret** [comment]
@DannyBen Released the new version of the gem: 
https://rubygems.org/gems/hashid-rails/versions/1.2.1

**Comment by DannyBen** [comment]
Cool, thanks for the quick fix.
