### ISSUE TITLE
Make to_param override optional

### ISSUE THREAD

**Issue by omitter** [jcypret/hashid-rails#58]
I'm trying hashid-rails without overriding the `find` method. I'd like to be explicit. Unfortunately, `to_params` is still overridden so can't use any code like `Model.find(model.to_params)` anymore. ActiveAdmin for instance does this and thus breaks.

Could you remove the `to_params` alias when `config.override_find = false` is set, or make it a separate option (`override_to_params`)?

**Comment by jcypret** [comment]
I like that idea. It makes sense for `override_to_params` to be a configurable option. And appreciate the use case of ActiveAdmin as well!

**Comment by jcypret** [comment]
Pushed a new version of the gem supporting an `override_to_params` configuration option  (#68). Appreciate the feedback!
