### ISSUE TITLE
hashid in json response

### ISSUE THREAD

**Issue by mirago** [jcypret/hashid-rails#6]
Hi, when the model is represented as json, it still has the id from the database rather than the hashid. I'm noob in rails, so I was wondering if there is an easy way to ovveride it for all models?

**Comment by jcypret** [comment]
It depends on what you are using to generate your json. The default implementation of this gem overrides the to `to_param` method on your model. Whenever you use a route helper in your app, such as `person_path(@person)`, Rails will call `to_param` on `@person`. 

If you are using something like ActiveModelSerializers, you can override the `id` method in the serializer to use the `to_param` method for getting the id:

```ruby
class PersonSerializer < ActiveModel::Serializer
  attribute :id
  
  def id
    object.to_param
  end
end
```
