### ISSUE TITLE
Query return on Select

### ISSUE THREAD

**Issue by hleow0707** [jcypret/hashid-rails#69]
hi there is there any way for it to return on .select query? example

Person.where(name: "Jason").select(:name, :hashid)

**Comment by jcypret** [comment]
Hi @hleow0707,

The hashids aren't stored in the database so there's no way to select them directly. But `hashid` is just a computed property derived from the `id`. So for the example above, to use a `select` to limit the columns retrieved, you would want to grab the `name` and `id`. That would make the `hashid` attribute available without any additional queries.

```ruby
person = Person.where(name: "Jason").select(:id, :name).first
# Post Load (0.3ms)  SELECT id, name FROM posts LIMIT 1
#=> #<Person id: 1, name: "Jason">
person.hashid
# (no additional query needed)
#=> "NYyt0N"
```

Hope that helps! Cheers.
